// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/2d/submaps_options_2d.proto

#include "cartographer/mapping/proto/2d/submaps_options_2d.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_cartographer_2fmapping_2fproto_2f2d_2fgrid_5f2d_5foptions_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GridOptions2D_cartographer_2fmapping_2fproto_2f2d_2fgrid_5f2d_5foptions_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_RangeDataInserterOptions_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto;
namespace cartographer {
namespace mapping {
namespace proto {
class SubmapsOptions2DDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SubmapsOptions2D> _instance;
} _SubmapsOptions2D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
static void InitDefaultsSubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cartographer::mapping::proto::_SubmapsOptions2D_default_instance_;
    new (ptr) ::cartographer::mapping::proto::SubmapsOptions2D();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cartographer::mapping::proto::SubmapsOptions2D::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_SubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsSubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto}, {
      &scc_info_GridOptions2D_cartographer_2fmapping_2fproto_2f2d_2fgrid_5f2d_5foptions_2eproto.base,
      &scc_info_RangeDataInserterOptions_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto.base,}};

void InitDefaults_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_SubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, num_range_data_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, grid_options_2d_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::SubmapsOptions2D, range_data_inserter_options_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cartographer::mapping::proto::SubmapsOptions2D)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cartographer::mapping::proto::_SubmapsOptions2D_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto = {
  {}, AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, "cartographer/mapping/proto/2d/submaps_options_2d.proto", schemas,
  file_default_instances, TableStruct_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto::offsets,
  file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, 1, file_level_enum_descriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, file_level_service_descriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto,
};

const char descriptor_table_protodef_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto[] =
  "\n6cartographer/mapping/proto/2d/submaps_"
  "options_2d.proto\022\032cartographer.mapping.p"
  "roto\0323cartographer/mapping/proto/2d/grid"
  "_2d_options.proto\032<cartographer/mapping/"
  "proto/range_data_inserter_options.proto\""
  "\311\001\n\020SubmapsOptions2D\022\026\n\016num_range_data\030\001"
  " \001(\005\022B\n\017grid_options_2d\030\002 \001(\0132).cartogra"
  "pher.mapping.proto.GridOptions2D\022Y\n\033rang"
  "e_data_inserter_options\030\003 \001(\01324.cartogra"
  "pher.mapping.proto.RangeDataInserterOpti"
  "onsb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto = {
  false, InitDefaults_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, 
  descriptor_table_protodef_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto,
  "cartographer/mapping/proto/2d/submaps_options_2d.proto", &assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, 411,
};

void AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[2] =
  {
    ::AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2fgrid_5f2d_5foptions_2eproto,
    ::AddDescriptors_cartographer_2fmapping_2fproto_2frange_5fdata_5finserter_5foptions_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto, deps, 2);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto = []() { AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto(); return true; }();
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

void SubmapsOptions2D::InitAsDefaultInstance() {
  ::cartographer::mapping::proto::_SubmapsOptions2D_default_instance_._instance.get_mutable()->grid_options_2d_ = const_cast< ::cartographer::mapping::proto::GridOptions2D*>(
      ::cartographer::mapping::proto::GridOptions2D::internal_default_instance());
  ::cartographer::mapping::proto::_SubmapsOptions2D_default_instance_._instance.get_mutable()->range_data_inserter_options_ = const_cast< ::cartographer::mapping::proto::RangeDataInserterOptions*>(
      ::cartographer::mapping::proto::RangeDataInserterOptions::internal_default_instance());
}
class SubmapsOptions2D::HasBitSetters {
 public:
  static const ::cartographer::mapping::proto::GridOptions2D& grid_options_2d(const SubmapsOptions2D* msg);
  static const ::cartographer::mapping::proto::RangeDataInserterOptions& range_data_inserter_options(const SubmapsOptions2D* msg);
};

const ::cartographer::mapping::proto::GridOptions2D&
SubmapsOptions2D::HasBitSetters::grid_options_2d(const SubmapsOptions2D* msg) {
  return *msg->grid_options_2d_;
}
const ::cartographer::mapping::proto::RangeDataInserterOptions&
SubmapsOptions2D::HasBitSetters::range_data_inserter_options(const SubmapsOptions2D* msg) {
  return *msg->range_data_inserter_options_;
}
void SubmapsOptions2D::clear_grid_options_2d() {
  if (GetArenaNoVirtual() == nullptr && grid_options_2d_ != nullptr) {
    delete grid_options_2d_;
  }
  grid_options_2d_ = nullptr;
}
void SubmapsOptions2D::clear_range_data_inserter_options() {
  if (GetArenaNoVirtual() == nullptr && range_data_inserter_options_ != nullptr) {
    delete range_data_inserter_options_;
  }
  range_data_inserter_options_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SubmapsOptions2D::kNumRangeDataFieldNumber;
const int SubmapsOptions2D::kGridOptions2DFieldNumber;
const int SubmapsOptions2D::kRangeDataInserterOptionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SubmapsOptions2D::SubmapsOptions2D()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.SubmapsOptions2D)
}
SubmapsOptions2D::SubmapsOptions2D(const SubmapsOptions2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_grid_options_2d()) {
    grid_options_2d_ = new ::cartographer::mapping::proto::GridOptions2D(*from.grid_options_2d_);
  } else {
    grid_options_2d_ = nullptr;
  }
  if (from.has_range_data_inserter_options()) {
    range_data_inserter_options_ = new ::cartographer::mapping::proto::RangeDataInserterOptions(*from.range_data_inserter_options_);
  } else {
    range_data_inserter_options_ = nullptr;
  }
  num_range_data_ = from.num_range_data_;
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.SubmapsOptions2D)
}

void SubmapsOptions2D::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_SubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto.base);
  ::memset(&grid_options_2d_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_range_data_) -
      reinterpret_cast<char*>(&grid_options_2d_)) + sizeof(num_range_data_));
}

SubmapsOptions2D::~SubmapsOptions2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.SubmapsOptions2D)
  SharedDtor();
}

void SubmapsOptions2D::SharedDtor() {
  if (this != internal_default_instance()) delete grid_options_2d_;
  if (this != internal_default_instance()) delete range_data_inserter_options_;
}

void SubmapsOptions2D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SubmapsOptions2D& SubmapsOptions2D::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SubmapsOptions2D_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto.base);
  return *internal_default_instance();
}


void SubmapsOptions2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.SubmapsOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && grid_options_2d_ != nullptr) {
    delete grid_options_2d_;
  }
  grid_options_2d_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && range_data_inserter_options_ != nullptr) {
    delete range_data_inserter_options_;
  }
  range_data_inserter_options_ = nullptr;
  num_range_data_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SubmapsOptions2D::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SubmapsOptions2D*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 num_range_data = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_num_range_data(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::cartographer::mapping::proto::GridOptions2D::_InternalParse;
        object = msg->mutable_grid_options_2d();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::cartographer::mapping::proto::RangeDataInserterOptions::_InternalParse;
        object = msg->mutable_range_data_inserter_options();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SubmapsOptions2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.SubmapsOptions2D)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num_range_data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_range_data_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_grid_options_2d()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_range_data_inserter_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.SubmapsOptions2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.SubmapsOptions2D)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SubmapsOptions2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.SubmapsOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_range_data = 1;
  if (this->num_range_data() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_range_data(), output);
  }

  // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
  if (this->has_grid_options_2d()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::grid_options_2d(this), output);
  }

  // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
  if (this->has_range_data_inserter_options()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::range_data_inserter_options(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.SubmapsOptions2D)
}

::google::protobuf::uint8* SubmapsOptions2D::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.SubmapsOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_range_data = 1;
  if (this->num_range_data() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_range_data(), target);
  }

  // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
  if (this->has_grid_options_2d()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::grid_options_2d(this), target);
  }

  // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
  if (this->has_range_data_inserter_options()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::range_data_inserter_options(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.SubmapsOptions2D)
  return target;
}

size_t SubmapsOptions2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.SubmapsOptions2D)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .cartographer.mapping.proto.GridOptions2D grid_options_2d = 2;
  if (this->has_grid_options_2d()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *grid_options_2d_);
  }

  // .cartographer.mapping.proto.RangeDataInserterOptions range_data_inserter_options = 3;
  if (this->has_range_data_inserter_options()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *range_data_inserter_options_);
  }

  // int32 num_range_data = 1;
  if (this->num_range_data() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_range_data());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SubmapsOptions2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  const SubmapsOptions2D* source =
      ::google::protobuf::DynamicCastToGenerated<SubmapsOptions2D>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.SubmapsOptions2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.SubmapsOptions2D)
    MergeFrom(*source);
  }
}

void SubmapsOptions2D::MergeFrom(const SubmapsOptions2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_grid_options_2d()) {
    mutable_grid_options_2d()->::cartographer::mapping::proto::GridOptions2D::MergeFrom(from.grid_options_2d());
  }
  if (from.has_range_data_inserter_options()) {
    mutable_range_data_inserter_options()->::cartographer::mapping::proto::RangeDataInserterOptions::MergeFrom(from.range_data_inserter_options());
  }
  if (from.num_range_data() != 0) {
    set_num_range_data(from.num_range_data());
  }
}

void SubmapsOptions2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SubmapsOptions2D::CopyFrom(const SubmapsOptions2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.SubmapsOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmapsOptions2D::IsInitialized() const {
  return true;
}

void SubmapsOptions2D::Swap(SubmapsOptions2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SubmapsOptions2D::InternalSwap(SubmapsOptions2D* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(grid_options_2d_, other->grid_options_2d_);
  swap(range_data_inserter_options_, other->range_data_inserter_options_);
  swap(num_range_data_, other->num_range_data_);
}

::google::protobuf::Metadata SubmapsOptions2D::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto);
  return ::file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2fsubmaps_5foptions_5f2d_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::cartographer::mapping::proto::SubmapsOptions2D* Arena::CreateMaybeMessage< ::cartographer::mapping::proto::SubmapsOptions2D >(Arena* arena) {
  return Arena::CreateInternal< ::cartographer::mapping::proto::SubmapsOptions2D >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
