// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/2d/tsdf_range_data_inserter_options_2d.proto

#include "cartographer/mapping/proto/2d/tsdf_range_data_inserter_options_2d.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_cartographer_2fmapping_2fproto_2f2d_2fnormal_5festimation_5foptions_5f2d_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_NormalEstimationOptions2D_cartographer_2fmapping_2fproto_2f2d_2fnormal_5festimation_5foptions_5f2d_2eproto;
namespace cartographer {
namespace mapping {
namespace proto {
class TSDFRangeDataInserterOptions2DDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TSDFRangeDataInserterOptions2D> _instance;
} _TSDFRangeDataInserterOptions2D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
static void InitDefaultsTSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cartographer::mapping::proto::_TSDFRangeDataInserterOptions2D_default_instance_;
    new (ptr) ::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto}, {
      &scc_info_NormalEstimationOptions2D_cartographer_2fmapping_2fproto_2f2d_2fnormal_5festimation_5foptions_5f2d_2eproto.base,}};

void InitDefaults_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_TSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, truncation_distance_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, maximum_weight_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, update_free_space_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, normal_estimation_options_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, project_sdf_distance_to_scan_normal_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, update_weight_range_exponent_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, update_weight_angle_scan_normal_to_ray_kernel_bandwith_),
  PROTOBUF_FIELD_OFFSET(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D, update_weight_distance_cell_to_hit_kernel_bandwith_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cartographer::mapping::proto::_TSDFRangeDataInserterOptions2D_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto = {
  {}, AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, "cartographer/mapping/proto/2d/tsdf_range_data_inserter_options_2d.proto", schemas,
  file_default_instances, TableStruct_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto::offsets,
  file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, 1, file_level_enum_descriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, file_level_service_descriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto,
};

const char descriptor_table_protodef_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto[] =
  "\nGcartographer/mapping/proto/2d/tsdf_ran"
  "ge_data_inserter_options_2d.proto\022\032carto"
  "grapher.mapping.proto\032@cartographer/mapp"
  "ing/proto/2d/normal_estimation_options_2"
  "d.proto\"\231\003\n\036TSDFRangeDataInserterOptions"
  "2D\022\033\n\023truncation_distance\030\001 \001(\001\022\026\n\016maxim"
  "um_weight\030\002 \001(\001\022\031\n\021update_free_space\030\003 \001"
  "(\010\022X\n\031normal_estimation_options\030\004 \001(\01325."
  "cartographer.mapping.proto.NormalEstimat"
  "ionOptions2D\022+\n#project_sdf_distance_to_"
  "scan_normal\030\005 \001(\010\022$\n\034update_weight_range"
  "_exponent\030\006 \001(\005\022>\n6update_weight_angle_s"
  "can_normal_to_ray_kernel_bandwith\030\007 \001(\001\022"
  ":\n2update_weight_distance_cell_to_hit_ke"
  "rnel_bandwith\030\010 \001(\001b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto = {
  false, InitDefaults_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, 
  descriptor_table_protodef_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto,
  "cartographer/mapping/proto/2d/tsdf_range_data_inserter_options_2d.proto", &assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, 587,
};

void AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2fnormal_5festimation_5foptions_5f2d_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto = []() { AddDescriptors_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto(); return true; }();
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

void TSDFRangeDataInserterOptions2D::InitAsDefaultInstance() {
  ::cartographer::mapping::proto::_TSDFRangeDataInserterOptions2D_default_instance_._instance.get_mutable()->normal_estimation_options_ = const_cast< ::cartographer::mapping::proto::NormalEstimationOptions2D*>(
      ::cartographer::mapping::proto::NormalEstimationOptions2D::internal_default_instance());
}
class TSDFRangeDataInserterOptions2D::HasBitSetters {
 public:
  static const ::cartographer::mapping::proto::NormalEstimationOptions2D& normal_estimation_options(const TSDFRangeDataInserterOptions2D* msg);
};

const ::cartographer::mapping::proto::NormalEstimationOptions2D&
TSDFRangeDataInserterOptions2D::HasBitSetters::normal_estimation_options(const TSDFRangeDataInserterOptions2D* msg) {
  return *msg->normal_estimation_options_;
}
void TSDFRangeDataInserterOptions2D::clear_normal_estimation_options() {
  if (GetArenaNoVirtual() == nullptr && normal_estimation_options_ != nullptr) {
    delete normal_estimation_options_;
  }
  normal_estimation_options_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TSDFRangeDataInserterOptions2D::kTruncationDistanceFieldNumber;
const int TSDFRangeDataInserterOptions2D::kMaximumWeightFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateFreeSpaceFieldNumber;
const int TSDFRangeDataInserterOptions2D::kNormalEstimationOptionsFieldNumber;
const int TSDFRangeDataInserterOptions2D::kProjectSdfDistanceToScanNormalFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightRangeExponentFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightAngleScanNormalToRayKernelBandwithFieldNumber;
const int TSDFRangeDataInserterOptions2D::kUpdateWeightDistanceCellToHitKernelBandwithFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TSDFRangeDataInserterOptions2D::TSDFRangeDataInserterOptions2D()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}
TSDFRangeDataInserterOptions2D::TSDFRangeDataInserterOptions2D(const TSDFRangeDataInserterOptions2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_normal_estimation_options()) {
    normal_estimation_options_ = new ::cartographer::mapping::proto::NormalEstimationOptions2D(*from.normal_estimation_options_);
  } else {
    normal_estimation_options_ = nullptr;
  }
  ::memcpy(&truncation_distance_, &from.truncation_distance_,
    static_cast<size_t>(reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwith_) -
    reinterpret_cast<char*>(&truncation_distance_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwith_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}

void TSDFRangeDataInserterOptions2D::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_TSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto.base);
  ::memset(&normal_estimation_options_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwith_) -
      reinterpret_cast<char*>(&normal_estimation_options_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwith_));
}

TSDFRangeDataInserterOptions2D::~TSDFRangeDataInserterOptions2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  SharedDtor();
}

void TSDFRangeDataInserterOptions2D::SharedDtor() {
  if (this != internal_default_instance()) delete normal_estimation_options_;
}

void TSDFRangeDataInserterOptions2D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TSDFRangeDataInserterOptions2D& TSDFRangeDataInserterOptions2D::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TSDFRangeDataInserterOptions2D_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto.base);
  return *internal_default_instance();
}


void TSDFRangeDataInserterOptions2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && normal_estimation_options_ != nullptr) {
    delete normal_estimation_options_;
  }
  normal_estimation_options_ = nullptr;
  ::memset(&truncation_distance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&update_weight_distance_cell_to_hit_kernel_bandwith_) -
      reinterpret_cast<char*>(&truncation_distance_)) + sizeof(update_weight_distance_cell_to_hit_kernel_bandwith_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TSDFRangeDataInserterOptions2D::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TSDFRangeDataInserterOptions2D*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // double truncation_distance = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 9) goto handle_unusual;
        msg->set_truncation_distance(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // double maximum_weight = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 17) goto handle_unusual;
        msg->set_maximum_weight(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // bool update_free_space = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_update_free_space(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::cartographer::mapping::proto::NormalEstimationOptions2D::_InternalParse;
        object = msg->mutable_normal_estimation_options();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // bool project_sdf_distance_to_scan_normal = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_project_sdf_distance_to_scan_normal(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int32 update_weight_range_exponent = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 48) goto handle_unusual;
        msg->set_update_weight_range_exponent(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // double update_weight_angle_scan_normal_to_ray_kernel_bandwith = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 57) goto handle_unusual;
        msg->set_update_weight_angle_scan_normal_to_ray_kernel_bandwith(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // double update_weight_distance_cell_to_hit_kernel_bandwith = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 65) goto handle_unusual;
        msg->set_update_weight_distance_cell_to_hit_kernel_bandwith(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TSDFRangeDataInserterOptions2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double truncation_distance = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (9 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &truncation_distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double maximum_weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (17 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &maximum_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool update_free_space = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &update_free_space_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_normal_estimation_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool project_sdf_distance_to_scan_normal = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &project_sdf_distance_to_scan_normal_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 update_weight_range_exponent = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (48 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &update_weight_range_exponent_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double update_weight_angle_scan_normal_to_ray_kernel_bandwith = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (57 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &update_weight_angle_scan_normal_to_ray_kernel_bandwith_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double update_weight_distance_cell_to_hit_kernel_bandwith = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (65 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &update_weight_distance_cell_to_hit_kernel_bandwith_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TSDFRangeDataInserterOptions2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->truncation_distance(), output);
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->maximum_weight(), output);
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->update_free_space(), output);
  }

  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::normal_estimation_options(this), output);
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->project_sdf_distance_to_scan_normal(), output);
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->update_weight_range_exponent(), output);
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwith = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwith() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->update_weight_angle_scan_normal_to_ray_kernel_bandwith(), output);
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwith = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwith() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->update_weight_distance_cell_to_hit_kernel_bandwith(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
}

::google::protobuf::uint8* TSDFRangeDataInserterOptions2D::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->truncation_distance(), target);
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->maximum_weight(), target);
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->update_free_space(), target);
  }

  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::normal_estimation_options(this), target);
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->project_sdf_distance_to_scan_normal(), target);
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->update_weight_range_exponent(), target);
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwith = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwith() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->update_weight_angle_scan_normal_to_ray_kernel_bandwith(), target);
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwith = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwith() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->update_weight_distance_cell_to_hit_kernel_bandwith(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  return target;
}

size_t TSDFRangeDataInserterOptions2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .cartographer.mapping.proto.NormalEstimationOptions2D normal_estimation_options = 4;
  if (this->has_normal_estimation_options()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *normal_estimation_options_);
  }

  // double truncation_distance = 1;
  if (this->truncation_distance() != 0) {
    total_size += 1 + 8;
  }

  // double maximum_weight = 2;
  if (this->maximum_weight() != 0) {
    total_size += 1 + 8;
  }

  // bool update_free_space = 3;
  if (this->update_free_space() != 0) {
    total_size += 1 + 1;
  }

  // bool project_sdf_distance_to_scan_normal = 5;
  if (this->project_sdf_distance_to_scan_normal() != 0) {
    total_size += 1 + 1;
  }

  // int32 update_weight_range_exponent = 6;
  if (this->update_weight_range_exponent() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->update_weight_range_exponent());
  }

  // double update_weight_angle_scan_normal_to_ray_kernel_bandwith = 7;
  if (this->update_weight_angle_scan_normal_to_ray_kernel_bandwith() != 0) {
    total_size += 1 + 8;
  }

  // double update_weight_distance_cell_to_hit_kernel_bandwith = 8;
  if (this->update_weight_distance_cell_to_hit_kernel_bandwith() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TSDFRangeDataInserterOptions2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  const TSDFRangeDataInserterOptions2D* source =
      ::google::protobuf::DynamicCastToGenerated<TSDFRangeDataInserterOptions2D>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
    MergeFrom(*source);
  }
}

void TSDFRangeDataInserterOptions2D::MergeFrom(const TSDFRangeDataInserterOptions2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_normal_estimation_options()) {
    mutable_normal_estimation_options()->::cartographer::mapping::proto::NormalEstimationOptions2D::MergeFrom(from.normal_estimation_options());
  }
  if (from.truncation_distance() != 0) {
    set_truncation_distance(from.truncation_distance());
  }
  if (from.maximum_weight() != 0) {
    set_maximum_weight(from.maximum_weight());
  }
  if (from.update_free_space() != 0) {
    set_update_free_space(from.update_free_space());
  }
  if (from.project_sdf_distance_to_scan_normal() != 0) {
    set_project_sdf_distance_to_scan_normal(from.project_sdf_distance_to_scan_normal());
  }
  if (from.update_weight_range_exponent() != 0) {
    set_update_weight_range_exponent(from.update_weight_range_exponent());
  }
  if (from.update_weight_angle_scan_normal_to_ray_kernel_bandwith() != 0) {
    set_update_weight_angle_scan_normal_to_ray_kernel_bandwith(from.update_weight_angle_scan_normal_to_ray_kernel_bandwith());
  }
  if (from.update_weight_distance_cell_to_hit_kernel_bandwith() != 0) {
    set_update_weight_distance_cell_to_hit_kernel_bandwith(from.update_weight_distance_cell_to_hit_kernel_bandwith());
  }
}

void TSDFRangeDataInserterOptions2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TSDFRangeDataInserterOptions2D::CopyFrom(const TSDFRangeDataInserterOptions2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSDFRangeDataInserterOptions2D::IsInitialized() const {
  return true;
}

void TSDFRangeDataInserterOptions2D::Swap(TSDFRangeDataInserterOptions2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TSDFRangeDataInserterOptions2D::InternalSwap(TSDFRangeDataInserterOptions2D* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(normal_estimation_options_, other->normal_estimation_options_);
  swap(truncation_distance_, other->truncation_distance_);
  swap(maximum_weight_, other->maximum_weight_);
  swap(update_free_space_, other->update_free_space_);
  swap(project_sdf_distance_to_scan_normal_, other->project_sdf_distance_to_scan_normal_);
  swap(update_weight_range_exponent_, other->update_weight_range_exponent_);
  swap(update_weight_angle_scan_normal_to_ray_kernel_bandwith_, other->update_weight_angle_scan_normal_to_ray_kernel_bandwith_);
  swap(update_weight_distance_cell_to_hit_kernel_bandwith_, other->update_weight_distance_cell_to_hit_kernel_bandwith_);
}

::google::protobuf::Metadata TSDFRangeDataInserterOptions2D::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto);
  return ::file_level_metadata_cartographer_2fmapping_2fproto_2f2d_2ftsdf_5frange_5fdata_5finserter_5foptions_5f2d_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D* Arena::CreateMaybeMessage< ::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D >(Arena* arena) {
  return Arena::CreateInternal< ::cartographer::mapping::proto::TSDFRangeDataInserterOptions2D >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
